name: Autograding (Notebook Execution with Prebuilt Codespaces)

on:
  workflow_dispatch:  	# Allows manual trigger
  repository_dispatch:  # Triggered by GitHub Classroom's autograding system

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout student repository
      uses: actions/checkout@v4

    - name: Use Devcontainer (Prebuilt Codespaces Environment)
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          echo "Running inside the Codespaces prebuilt devcontainer!"
          echo "Python version:"
          python --version
          echo "Installed packages:"
          pip list
          
          echo "Searching for notebooks in all subdirectories..."
          notebook_count=$(find . -type f -name "*.ipynb" | wc -l)
          echo "Found $notebook_count notebooks."
          
          if [ "$notebook_count" -eq 0 ]; then
            echo "No notebooks found. Skipping execution."
          else
            # Execute all notebooks recursively
            find . -type f -name "*.ipynb" | while read notebook; do
              echo "Executing $notebook..."
              jupyter nbconvert --to notebook --execute "$notebook" --inplace --ExecutePreprocessor.timeout=600 \
                && echo "Successfully executed $notebook" \
                || echo "Execution failed for $notebook"
            done
          fi
          
          echo "Notebook execution completed."

    - name: Commit executed notebooks
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        git add *.ipynb
        git commit -m "Autograded: Executed notebooks with outputs" || echo "No changes to commit"
        git push origin ${{ steps.repo-info.outputs.REF }} || echo "No changes to push"
