name: Autograding (Notebook Execution with GitHub Codespaces)

on:
  workflow_dispatch:    # Allows manual trigger
  repository_dispatch:  # Triggered by GitHub Classroom's autograding system

jobs:
  execute-notebook:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # only needed to push executed notebooks back        

    steps:
    - name: Checkout student repository
      uses: actions/checkout@v4

    - name: Build and run inside devcontainer
      uses: devcontainers/ci@v0.3
      with:
        push: never     # build locally for this job only
        runCmd: |
          set -euo pipefail
          IFS=$'\n\t'
          echo "Executing all notebooks, allowing errors, forcing python3 kernel"
                    
          # Ensure required execution packages exist
          python -m pip install --no-cache-dir -q --upgrade pip
          python -m pip install --no-cache-dir -q nbconvert>=7.16 nbclient>=0.10 ipykernel>=6.29
          
          # Execute every tracked notebook; DO NOT fail the job on cell errors
          # Allow_errors=True ensures nbconvert keeps running and records tracebacks in outputs
          git ls-files -z '*.ipynb' | while IFS= read -r -d '' nb; do
            echo "Running notebook: $nb"
            jupyter nbconvert \
              --to notebook \
              --execute "$nb" \
              --inplace \
              --ExecutePreprocessor.kernel_name=python3 \
              --ExecutePreprocessor.timeout=600 \
              --ExecutePreprocessor.allow_errors=True
          done

    - name: Commit executed notebooks
      if: always()
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add -u
        git commit -m "Executed notebooks with outputs" || echo "No changes to commit"
        git push origin "${{ github.ref_name }}"
